### ISSUE TITLE
Multiple Different designSize

### ISSUE THREAD

**Issue by A7MeDG0L0L** [OpenFlutter/flutter_screenutil#481] opened 2023-05-20 01:40 UTC
What if I have multiple desingSize in Figma for example 
I have These  first one is Size(365, 1060) for mobile, 
Second one is Size(1440, 1440) for Web,
and it declared once here 
<img width="634" alt="image" src="https://github.com/OpenFlutter/flutter_screenutil/assets/33913003/f2287cd0-213d-4b8a-babd-cca62b030610">

I tried use that function inside build method for mobile and web widgets 

```
 ScreenUtil.init(
      context,
// for web 
      designSize: const Size(1440, 1440), // for mobile Size(365,1060) 
    );
```
but I think isn't works well.

**Comment by RomanSoviak** [comment] 2023-07-11 09:41
Need this feature as well

**Comment by Mounir-Bouaiche** [comment] 2023-07-21 08:55
Duplicate of #469

**Closed by Mounir-Bouaiche** 2023-07-21 08:55 UTC
