### ISSUE TITLE
Rebuild not triggered in const widget when screen is resized

### ISSUE THREAD

**Issue by brunoalod** [OpenFlutter/flutter_screenutil#327] opened 2022-01-22 15:08 UTC
Tried on 5.1.0.

When the screen is resized, it won't trigger a rebuild on const widget.

Using MediaQuery does trigger a rebuild.

**Comment by lizhuoyuan** [comment] 2022-01-24 02:37
What about removing the const?

**Comment by AhmedLSayed9** [comment] 2022-01-25 15:10
Duplicate of #312 

This has been fixed with the new `setContext` parameter. but for ".h , .w etc.." to work as MediaQuery you need to use latest version from GitHub as latest commit not yet published to pub.dev.

**Comment by mohamedamara** [comment] 2022-02-12 09:07
Same problem here, I'm using the latest version 5.2.0, removing the const keyword is not a solution we all know the the benefits of const .

**Closed** 2022-02-14 03:38 UTC

**Comment by brunoalod** [comment] 2022-02-17 14:03
This is not fixed. Tried resizing the window on Windows and it did not trigger a rebuild.

I came to the conclusion that this is impossible because of the extension on num. It doesn't pass a context. It should so that it behaves like MediaQuery.

**Comment by mirland** [comment] 2022-03-07 20:50
@lizhuoyuan Can you clarify that? I tested the sample app, and it seems that the resizing is not calling the rebuild

https://user-images.githubusercontent.com/8472881/157115726-0476912b-ee2b-4495-91df-531884b32df4.mp4

**Comment by lizhuoyuan** [comment] 2022-03-08 02:19
> @lizhuoyuan Can you clarify that? I tested the sample app, and it seems that the resizing is not calling the rebuild
> 
>  screen_size.mp4

should delete `const`

**Comment by mirland** [comment] 2022-03-08 13:24
Thanks, it's working fine! Maybe we can add something in the readme to clarify that
