### ISSUE TITLE
Different design sizes for different screens

### ISSUE THREAD

**Issue by RomanSoviak** [OpenFlutter/flutter_screenutil#497] opened 2023-07-11 09:48 UTC
I had design for screens with the following resolution: 375x812. So I added:
```
    ScreenUtil.init(
                  context,
                  designSize: Size(375, 812),
                  minTextAdapt: true,
                );
```
                
  Now we have a new designer and she makes new screens with another screen resolution:
              ` 375x667,`
               
 I want to make new screen uses new resoltion and the old ones designSize: 375x812,
How can I make to do it?

**Comment by Mounir-Bouaiche** [comment] 2023-07-21 08:56
Duplicate of #469

**Closed by Mounir-Bouaiche** 2023-07-21 08:56 UTC

**Comment by yuktaatreya** [comment] 2024-03-04 08:13
> Duplicate of #469

This is not a duplicate, in #469 updating the design size based on the condition updates the design size for the entire app. You cannot update the design size for just one screen. eg: If I add _ScreenUtil.init(context, designSize: const Size(375, 812));_ in the build method for one widget, rest of the widgets in the tree also get the updated design size. Need a way to define design size for only the child widget.
